name: Deploy Orin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout repo to $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: Compile SCSS
        run: |
          npm install -g sass
          sass --style=compressed --no-source-map src/scss/style.scss:style.css src/scss/mq.scss:css/mq.css
          
      - name: Minify JavaScript
        run: |
          npm install -g uglify-js
          uglifyjs --compress --mangle --output js/iframe-resizer.js -- js/iframe-resizer.js

      - name: Deploy to blog.founddrama.net
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "*.php,*.md,STARKERS_LICENSE.txt,css/*,images/*,js/*,languages/*,screenshot.png,style.css"
          target: blog.founddrama.net/wp-content/themes/orin
          overwrite: true
